# Generated by Django 2.1.7 on 2019-05-09 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '关注管理',
                'verbose_name_plural': '关注管理',
                'db_table': 'attention',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '收藏管理',
                'verbose_name_plural': '收藏管理',
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=2048, verbose_name='评论的内容')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='GitLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliendid', models.CharField(max_length=256, verbose_name='CliendID')),
            ],
            options={
                'verbose_name': 'githup登录管理',
                'verbose_name_plural': 'githup登录管理',
                'db_table': 'gitlogin',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, '点赞'), (False, '取消')], default=True, verbose_name='点赞状态')),
            ],
            options={
                'verbose_name': '点赞管理',
                'verbose_name_plural': '点赞管理',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=2048, verbose_name='发送的信息')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '私信管理',
                'verbose_name_plural': '私信管理',
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='发布内容')),
                ('datatime', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '发布管理',
                'verbose_name_plural': '发布管理',
                'db_table': 'release',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='user/default.jpg', upload_to='user/', verbose_name='用户头像')),
                ('username', models.CharField(max_length=256, verbose_name='用户名')),
                ('hash_password', models.CharField(max_length=256, verbose_name='密码')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=16, verbose_name='手机号')),
                ('location', models.CharField(max_length=256, null=True, verbose_name='所在地')),
                ('signature', models.TextField(null=True, verbose_name='个性签名')),
                ('register', models.DateField(auto_now=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='release',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='发布用户'),
        ),
        migrations.AddField(
            model_name='personal',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='application.User', verbose_name='发送用户'),
        ),
        migrations.AddField(
            model_name='personal',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='application.User', verbose_name='接受用户'),
        ),
        migrations.AddField(
            model_name='like',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Release', verbose_name='点赞的作品'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='gitlogin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Release', verbose_name='评论的作品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='collection',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Release', verbose_name='收藏的文章'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='attention',
            name='attention_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_user', to='application.User', verbose_name='被关注的用户'),
        ),
        migrations.AddField(
            model_name='attention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='gitlogin',
            unique_together={('cliendid',)},
        ),
    ]
